export const HOME = "/"
export const LOGIN = "/login"
export const SIGNUP = "/signup"
export const PROFILE = "/profile"
export const FORGOT = "/forgot"
export const OTP = "/otp"
export const CHANGE_PASSWORD = "changepass"
export const CHAT = "/chat"